spring:
  application:
    name: market
  datasource:
    username: root
    password: no_password
    database: market
    url: "jdbc:mariadb://localhost:3306"
  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    url: jdbc:mariadb://localhost:3306
    user: root
    password: no_password
    schemas: market
    locations: classpath:db/migration/mariadb